version: '3.8'
services: 
  api:
    build: .
    depends_on: 
      - database
    links:
      - database
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT 
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/usr/src/server
  database:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT