name: test_execute

on:
  pull_request:
    branches: "dev"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start docker compose
        run: docker-compose up -d 
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
